name: Renovate
on:
  push:
  schedule:
    - cron: '0/10 * * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: renovatebot/github-action@v39.2.3
        with:
          renovate-version: full
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: renovate-config.js
      - uses: fastify/github-action-merge-dependabot@v3.10.1
